import 'package:gmoria/models/PersonModel.dart';

List<Person> personsList = [
  Person(
    image: 'assets/images/person1.PNG',
    name: 'Darbellay',
    firstname: 'Richard',
    notes: '',
    id: 1,
  ),
  Person(
    image: 'assets/images/person2.PNG',
    name: 'Evéquoz',
    firstname: 'André',
    notes: '',
    id: 2,
  ),
  Person(
    image: 'assets/images/person3.PNG',
    name: 'Hubert',
    firstname: 'Alice',
    notes: '',
    id: 3,
  ),
  Person(
    image: 'assets/images/person3.PNG',
    name: 'Gerber',
    firstname: 'Roberte',
    notes: '',
    id: 4,
  ),
  Person(
    image: 'assets/images/person4.PNG',
    name: 'Rochat',
    firstname: 'Yvan',
    notes: '',
    id: 5,
  ),
  Person(
    image: 'assets/images/person5.PNG',
    name: 'Favre',
    firstname: 'Marie',
    notes: '',
    id: 6,
  ),
  Person(
    image: 'assets/images/person1.PNG',
    name: 'Aymon',
    firstname: 'Jean-Pierre',
    notes: '',
    id: 7,
  ),
  Person(
    image: 'assets/images/person2.PNG',
    name: 'Aubry',
    firstname: 'Yvonne',
    notes: '',
    id: 8,
  ),
  Person(
    image: 'assets/images/person3.PNG',
    name: 'Müller',
    firstname: 'François',
    notes: '',
    id: 9,
  ),
  Person(
    image: 'assets/images/person4.PNG',
    name: 'Morand',
    firstname: 'Josette',
    notes: '',
    id: 10,
  ),
  Person(
    image: 'assets/images/person1.PNG',
    name: 'Darbellay',
    firstname: 'Rick',
    notes: '',
    id: 11,
  ),
  Person(
    image: 'assets/images/person2.PNG',
    name: 'Hubert',
    firstname: 'André',
    notes: '',
    id: 12,
  ),
  Person(
    image: 'assets/images/person3.PNG',
    name: 'Hubert',
    firstname: 'Roberte',
    notes: '',
    id: 13,
  ),
  Person(
    image: 'assets/images/person3.PNG',
    name: 'Gerber',
    firstname: 'Roberte',
    notes: '',
    id: 14,
  ),
  Person(
    image: 'assets/images/person4.PNG',
    name: 'Rochat',
    firstname: 'François',
    notes: '',
    id: 15,
  ),
  Person(
    image: 'assets/images/person5.PNG',
    name: 'Gerber',
    firstname: 'Yvan',
    notes: '',
    id: 16,
  ),
  Person(
    image: 'assets/images/person1.PNG',
    name: 'Aymon',
    firstname: 'Jean-Pierre',
    notes: '',
    id: 17,
  ),
  Person(
    image: 'assets/images/person2.PNG',
    name: 'Aubry',
    firstname: 'Yvonne',
    notes: '',
    id: 18,
  ),
  Person(
    image: 'assets/images/person3.PNG',
    name: 'Müller',
    firstname: 'Josette',
    notes: '',
    id: 19,
  ),
  Person(
    image: 'assets/images/person4.PNG',
    name: 'Rochat',
    firstname: 'Josette',
    notes: '',
    id: 20,
  ),
];
